openapi: 3.0.0
info:
  title: Game Hub Manager API
  description: Detailed API documentation for the Game Hub Manager Interface.
  version: 1.0.0

servers:
  - url: /api
    description: Local API server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_token

paths:
  # --- AUTH ---
  /auth/login:
    post:
      tags: [Auth]
      summary: Login
      description: Authenticate user with email and password. Sets a session cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  user: { $ref: '#/components/schemas/User' }
        400: { description: Email or password required }
        401: { description: Invalid credentials }
        403: { description: Account disabled }

  /auth/logout:
    get:
      tags: [Auth]
      summary: Logout (GET)
      description: Clears session cookie and redirects to login.
      responses:
        302: { description: Redirect to /login }
    post:
      tags: [Auth]
      summary: Logout (POST)
      description: Clears session cookie and redirects to login.
      responses:
        302: { description: Redirect to /login }

  /auth/me:
    get:
      tags: [Auth]
      summary: Get current user
      description: Returns information about the currently logged-in user.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user: { $ref: '#/components/schemas/User' }
        401: { description: Unauthorized }

  # --- GAMES ---
  /games/list:
    get:
      tags: [Games]
      summary: List games
      description: Returns a list of games based on user roles and filters.
      parameters:
        - name: status
          in: query
          schema: { type: string }
        - name: ownerId
          in: query
          schema: { type: string }
        - name: subject
          in: query
          schema: { type: string }
        - name: grade
          in: query
          schema: { type: string }
        - name: isDeleted
          in: query
          schema: { type: boolean }
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items: { $ref: '#/components/schemas/GameWithVersion' }
        401: { description: Unauthorized }

  /games/create:
    post:
      tags: [Games]
      summary: Create game
      description: Creates a new game and an initial version (1.0.0).
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/GameCreateInput' }
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  game: { $ref: '#/components/schemas/Game' }
                  version: { $ref: '#/components/schemas/GameVersion' }
        400: { description: Validation error or Game ID exists }
        403: { description: Forbidden }

  /games/upload:
    post:
      tags: [Games]
      summary: Upload game ZIP
      description: Uploads a ZIP file containing the game build, validates the manifest, and creates/updates game and version records.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file: { type: string, format: binary, description: "ZIP file containing game build" }
                gameId: { type: string, description: "Game slug (e.g., com.iruka.math)" }
                version: { type: string, description: "SemVer version (e.g., 1.0.0)" }
                mongoGameId: { type: string, description: "Optional MongoDB ID for updates" }
      responses:
        200: { description: OK }
        400: { description: Missing fields or invalid ZIP }
        403: { description: Forbidden }

  /games/ids:
    get:
      tags: [Games]
      summary: Get all game IDs
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ids: { type: array, items: { type: string } }

  /games/update-metadata:
    post:
      tags: [Games]
      summary: Update game metadata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gameId: { type: string }
                updates: { type: object }
      responses:
        200: { description: OK }

  /games/delete:
    post:
      tags: [Games]
      summary: Delete or hard delete game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gameId: { type: string }
                hardDelete: { type: boolean }
      responses:
        200: { description: OK }

  /games/set-active:
    post:
      tags: [Games]
      summary: Set game active status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gameId: { type: string }
                isActive: { type: boolean }
      responses:
        200: { description: OK }

  /games/submit-qc:
    post:
      tags: [Games]
      summary: Submit for QC review
      description: Dev submits a version (draft or qc_failed) for QC review.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                versionId: { type: string }
                gameId: { type: string }
      responses:
        200: { description: OK }
        400: { description: Self-QA incomplete or invalid status }

  /games/self-qa:
    post:
      tags: [Games]
      summary: Update Self-QA checklist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                versionId: { type: string }
                gameId: { type: string }
                checklist: { $ref: '#/components/schemas/SelfQAChecklist' }
                note: { type: string }
      responses:
        200: { description: OK }

  /games/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      tags: [Games]
      summary: Get game details
      responses:
        200: { description: OK }
        404: { description: Not found }

  /games/{id}/update:
    post:
      tags: [Games]
      summary: Update game
      description: Updates basic game metadata.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/GameUpdateInput' }
      responses:
        200: { description: OK }

  /games/{id}/publish:
    post:
      tags: [Games]
      summary: Publish game version
      description: Changes version status from approved to published and sets as live (Admin only).
      responses:
        200: { description: OK }
        400: { description: Error }
        403: { description: Forbidden }

  /games/{id}/approve:
    post:
      tags: [Games]
      summary: Approve or Reject game version
      description: CTO/CEO/Admin approves or rejects a version after QC passed.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                decision: { type: string, enum: [approve, reject] }
                notes: { type: string }
      responses:
        200: { description: OK }
        400: { description: Invalid decision or status }

  /games/{id}/qc-review:
    post:
      tags: [Games]
      summary: Submit QC Review
      description: QC submits review result (Pass/Fail) with report.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                versionId: { type: string }
                decision: { type: string, enum: [pass, fail] }
                qaSummary: { type: object }
                notes: { type: string }
                reviewerName: { type: string }
      responses:
        200: { description: OK }
        400: { description: Invalid data or status }

  /games/{id}/set-live:
    post:
      tags: [Games]
      summary: Set live version
      description: Manually set a specific published version as live.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                versionId: { type: string, description: "Required if latestVersionId is not used" }
      responses:
        201: { description: OK }

  /games/{id}/versions:
    get:
      tags: [Games]
      summary: List game versions
      description: Returns all versions for a specific game.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/GameVersion' }

  /games/upload-thumbnail:
    post:
      tags: [Games]
      summary: Upload thumbnail
      description: Uploads a thumbnail image for a game. Uses multipart/form-data.
      responses:
        200: { description: OK }

  # --- USERS ---
  /users:
    get:
      tags: [Users]
      summary: List users
      description: Admin/CTO only. Returns list of all users.
      responses:
        200: { description: OK }
    post:
      tags: [Users]
      summary: Create user
      description: Admin/CTO only. Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
                name: { type: string }
                roles: { type: array, items: { type: string } }
      responses:
        201: { description: Created }

  /users/{id}/status:
    post:
      tags: [Users]
      summary: Update user status
      description: Enable or disable a user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isActive: { type: boolean }
      responses:
        200: { description: OK }

  /users/{id}/password:
    post:
      tags: [Users]
      summary: Reset user password
      responses:
        200: { description: OK }

  # --- SYSTEM ---
  /dashboard/stats:
    get:
      tags: [System]
      summary: Get dashboard statistics
      description: Returns counts of games by status and recent activities.
      responses:
        200: { description: OK }

  /audit-logs:
    get:
      tags: [System]
      summary: List audit logs
      description: System:audit_view permission required.
      parameters:
        - name: userId
          in: query
          schema: { type: string }
        - name: action
          in: query
          schema: { type: string }
        - name: targetId
          in: query
          schema: { type: string }
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: limit
          in: query
          schema: { type: integer, default: 50 }
      responses:
        200: { description: OK }

  /notifications:
    get:
      tags: [System]
      summary: Get notifications
      responses:
        200: { description: OK }
    post:
      tags: [System]
      summary: Mark notification as read
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                notificationId: { type: string }
                markAllRead: { type: boolean }
      responses:
        200: { description: OK }

  # --- EXTERNAL ---
  /qc/run:
    post:
      tags: [QC]
      summary: Run QC check
      description: Triggers an automated QC check for a specific version.
      responses:
        200: { description: OK }

  /gcs/files:
    get:
      tags: [GCS]
      summary: List storage files
      parameters:
        - name: path
          in: query
          schema: { type: string }
      responses:
        200: { description: OK }

components:
  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        name: { type: string }
        roles: { type: array, items: { type: string } }
        avatar: { type: string }
        isActive: { type: boolean }

    Game:
      type: object
      properties:
        _id: { type: string }
        gameId: { type: string }
        title: { type: string }
        description: { type: string }
        ownerId: { type: string }
        subject: { type: string }
        grade: { type: string }
        status: { type: string, description: "Deprecated" }
        latestVersionId: { type: string }
        liveVersionId: { type: string }
        isDeleted: { type: boolean }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }

    GameWithVersion:
      allOf:
        - $ref: '#/components/schemas/Game'
        - type: object
          properties:
            latestVersion:
              type: object
              properties:
                _id: { type: string }
                version: { type: string }
                status: { type: string }
                submittedAt: { type: string, format: date-time }
            liveVersion:
              type: object
              properties:
                _id: { type: string }
                version: { type: string }

    GameVersion:
      type: object
      properties:
        _id: { type: string }
        gameId: { type: string }
        version: { type: string }
        status: { type: string, enum: [draft, uploaded, qc_passed, qc_failed, approved, rejected, published] }
        storagePath: { type: string }
        entryFile: { type: string }
        submittedBy: { type: string }
        submittedAt: { type: string, format: date-time }
        selfQAChecklist: { $ref: '#/components/schemas/SelfQAChecklist' }

    SelfQAChecklist:
      type: object
      properties:
        testedDevices: { type: boolean }
        testedAudio: { type: boolean }
        gameplayComplete: { type: boolean }
        contentVerified: { type: boolean }
        note: { type: string }

    GameCreateInput:
      type: object
      required: [title, gameId]
      properties:
        title: { type: string }
        gameId: { type: string }
        subject: { type: string }
        grade: { type: string }
        unit: { type: string }
        gameType: { type: string }
        priority: { type: string }
        description: { type: string }

    GameUpdateInput:
      type: object
      properties:
        title: { type: string }
        subject: { type: string }
        grade: { type: string }
        description: { type: string }
        unit: { type: string }
        gameType: { type: string }
        priority: { type: string }
